# Generated by Django 5.2 on 2025-05-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(upload_to='kurs_rasmlari/')),
                ('daraja', models.CharField(choices=[('boshlovchi', 'Boshlovchi'), ('orta', 'O‘rta'), ('ilgor', 'Ilg‘or')], max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('tartib', models.PositiveIntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurslar.kurs')),
            ],
            options={
                'ordering': ['tartib'],
            },
        ),
    ]
